package mainRun.bean;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.validation.constraints.NotNull;
import java.util.Date;

public class SpdUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spd_user.id
     *
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spd_user.username
     *
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    @NotNull
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spd_user.password
     *
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spd_user.sex
     *
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spd_user.email
     *
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spd_user.cjsj
     *
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spd_user.xgsj
     *
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    private Date xgsj;

    private Integer age;

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spd_user.id
     *
     * @return the value of spd_user.id
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spd_user.id
     *
     * @param id the value for spd_user.id
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spd_user.username
     *
     * @return the value of spd_user.username
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spd_user.username
     *
     * @param username the value for spd_user.username
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spd_user.password
     *
     * @return the value of spd_user.password
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spd_user.password
     *
     * @param password the value for spd_user.password
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spd_user.sex
     *
     * @return the value of spd_user.sex
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spd_user.sex
     *
     * @param sex the value for spd_user.sex
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spd_user.email
     *
     * @return the value of spd_user.email
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spd_user.email
     *
     * @param email the value for spd_user.email
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spd_user.cjsj
     *
     * @return the value of spd_user.cjsj
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH-mm-ss", timezone = "GMT+8")
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spd_user.cjsj
     *
     * @param cjsj the value for spd_user.cjsj
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spd_user.xgsj
     *
     * @return the value of spd_user.xgsj
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spd_user.xgsj
     *
     * @param xgsj the value for spd_user.xgsj
     * @mbg.generated Mon Jan 14 17:33:01 CST 2019
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }
}